Repository crux-arm/crux-arm-release, pull requests merged in 2022-12, with the labels that each got.

#18 Added xz compression mode to tar
  Makefile
Labels: bug, enhancement

#21 Freeze version of upstream ports
  Makefile
Labels: enhancement

#20 Export DEVICE_OPTIMIZATION variable to sub-make commands. This should…
  Makefile
Labels: bug

#23 tools/overlay-diff: initial import
  tools/overlay-diff
Labels: enhancement

#25 Update CRUX_GIT_HASH which includes some fixes
  Makefile
Labels: bug

#24 Fix to be able to reuse stage0 from bootstrap
  Makefile
Labels: bug, enhancement
